# =============================================================================
# ECLIPSE DITTO - DIGITAL TWIN PLATFORM
# =============================================================================
# Standalone Ditto deployment integrated with DigitalEgiz
# Based on official Eclipse Ditto deployment
# =============================================================================

version: '3.8'

services:

  # MongoDB Database for Ditto
  mongodb:
    image: mongo:7.0
    container_name: digitalegiz-mongodb
    restart: unless-stopped
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
    networks:
      - digitalegiz-network

  # Ditto Policies Service
  ditto-policies:
    image: eclipse/ditto-policies:${DITTO_VERSION}
    container_name: digitalegiz-ditto-policies
    hostname: policies
    restart: unless-stopped
    environment:
      - MONGO_DB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/policies
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx256m
    depends_on:
      - mongodb
    networks:
      digitalegiz-network:
        aliases:
          - ditto-cluster

  # Ditto Things Service
  ditto-things:
    image: eclipse/ditto-things:${DITTO_VERSION}
    container_name: digitalegiz-ditto-things
    hostname: things
    restart: unless-stopped
    environment:
      - MONGO_DB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/things
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx256m
    depends_on:
      - mongodb
      - ditto-policies
    networks:
      digitalegiz-network:
        aliases:
          - ditto-cluster

  # Ditto Things Search Service
  ditto-things-search:
    image: eclipse/ditto-things-search:${DITTO_VERSION}
    container_name: digitalegiz-ditto-things-search
    hostname: things-search
    restart: unless-stopped
    environment:
      - MONGO_DB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/searchDB
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      - mongodb
      - ditto-policies
      - ditto-things
    networks:
      digitalegiz-network:
        aliases:
          - ditto-cluster

  # Ditto Connectivity Service (MQTT Integration)
  ditto-connectivity:
    image: eclipse/ditto-connectivity:${DITTO_VERSION}
    container_name: digitalegiz-ditto-connectivity
    hostname: connectivity
    restart: unless-stopped
    environment:
      - MONGO_DB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/connectivity
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      - mongodb
      - ditto-policies
      - ditto-things
    networks:
      digitalegiz-network:
        aliases:
          - ditto-cluster

  # Ditto Gateway Service (API Entry Point)
  ditto-gateway:
    image: eclipse/ditto-gateway:${DITTO_VERSION}
    container_name: digitalegiz-ditto-gateway
    hostname: gateway
    restart: unless-stopped
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
      - DEVOPS_PASSWORD=${DITTO_DEVOPS_PASSWORD}
      - ENABLE_PRE_AUTHENTICATION=true
    depends_on:
      - ditto-policies
      - ditto-things
      - ditto-things-search
      - ditto-connectivity
    networks:
      digitalegiz-network:
        aliases:
          - ditto-cluster

  # Ditto UI (Web Interface)
  ditto-ui:
    image: eclipse/ditto-ui:${DITTO_VERSION}
    container_name: digitalegiz-ditto-ui
    hostname: ditto-ui
    restart: unless-stopped
    networks:
      - digitalegiz-network

  # Nginx Reverse Proxy for Ditto
  ditto-nginx:
    image: nginx:1.27-alpine
    container_name: digitalegiz-ditto-nginx
    hostname: ditto-nginx
    restart: unless-stopped
    volumes:
      - ./configuration/ditto/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configuration/ditto/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
      - ./configuration/ditto/nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
    depends_on:
      - ditto-gateway
      - ditto-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ditto.rule=Host(`ditto.${DOMAIN}`)"
      - "traefik.http.routers.ditto.tls=true"
      - "traefik.http.routers.ditto.tls.certresolver=letsencrypt"
      - "traefik.http.services.ditto.loadbalancer.server.port=8080"
    networks:
      - digitalegiz-network

volumes:
  mongodata:

networks:
  digitalegiz-network:
    external: true
